version: "3"

services:
  pihole:
    mac_address: de:ad:be:ef:ff:01
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      docker_net:
        ipv4_address: 192.168.0.192
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'pass1234'
      ServerIP: 192.168.0.192
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
networks:
  docker_net:
    external:
      name: docker_net
